### PR TITLE
minted: fix linenos in PDF & fix clean rules

### PR DESCRIPTION
**Pull request by Elfikurr**
For the Makefiles : if corrects the clean rules, so that we can `make clean` from the top folder.

For minted, it overrides the  `theFancyVerbLine` macro in order to remove the line numbers in the PDF, thus preventing them from being copy-pasted. They will be replaced by nothing, but will still be shown, thanks to `ActualText={}`.

### CODE REVIEW

**Review by Nhqml — APPROVED** [review]
**Very neat** feature! However it does not work on every PDF reader (I would say it's their fault)

Finding a way to keep the indentation would be awesome :wink:

**Comment by Elfikurr** [comment]
Does my change break the indentation ?

What does not work on every PDF reader, the indentation or the "line number copying" ?

**Comment by Nhqml** [comment]
No, I believe your change does not break anything but seems to have no effect on some PDF readers.

Regarding the indentation, I was suggesting that if you found a similar fix that would allow to keep the indentation when copy/pasting it would also be an awesome improvement :wink:

**Comment by Elfikurr** [comment]
Ok I see.

I remember I found some threads talking about this, I'll look into it :)

**Review by Nhqml — APPROVED** [review]

**Pull request merged**
