### PR TITLE
minted: configuration improvements

### PR DESCRIPTION
**Pull request by Nhqml**
Multiple configuration improvements:

- remove the red box drawn in case of syntax error
- add automatic line breaks in code snippets
- force code snippets to fit on a single page

### CODE REVIEW

**Comment by Nhqml** [comment]
Here is why we don't want minted to draw a box
image
image

**Comment by 71** [comment]
Kenji, language.

**Comment by Elfikurr** [comment]
Thank you for this, however, please edit this PR and the commit in order to remove the inappropriate language : this repository is public and young people might see this.

**Review by Elfikurr — APPROVED** [review]
LGTM, thanks a log :)

**Pull request merged**
